### ISSUE TITLE
Warning about SLF4J

### ISSUE THREAD

**Issue by magnars** [cjohansen/asciidoclj#1]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Seems like it's a matter of adding a dependency.

http://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder

**Comment by cjohansen** [comment]
How did you get the error? I've never seen it, so I'm not sure if I fixed it with this commit. It didn't introduce any new ones at least :)

**Comment by magnars** [comment]
Just starting an app with this dependency in it. But yeah, this fixed it. :)
